### ISSUE TITLE
Resizing video Inquiry

### ISSUE THREAD

**Issue by nsalc050** [krzysieksr/KS_Traffic_Analyzer#3]
Hi,

Is it possible to resize the GUI to actual aspect ratio with respect to the video?

Thanks.

**Comment by nsalc050** [comment]
Could you also explain what do the video threshold,History,area threshold fields from the GUI mean

**Comment by Mudassir32** [comment]
Specific threshold values are required for selecting an area for counting
vehicles.
You can change threshold values for selecting another area.


--
Regards

Mudassir Mehmood

**Comment by Mudassir32** [comment]
Need to check.

What are you trying to do, explain your overall scope, please?


--
Regards

Mudassir Mehmood

**Comment by nsalc050** [comment]
Hi ,
 I want to upload a video to check to car count , the problem is the video is taken in landscape mode, the application stretches  out the video, as shown in the pictures. This makes the counting line not count accurately. 
Could you tell us where in the code , this re-sizing function is happening?
Also I understand that the vehicle size threshold changes the size of detecting vehicles. but I do not know how exactly area threshold, video threshold, and history are affecting the video.
![29954825_10215601679852742_757734449_o](https://user-images.githubusercontent.com/31559354/38208358-cf3cd610-367e-11e8-9669-64b2e907c7cd.jpg)
![29993867_10215601679812741_28770548_o](https://user-images.githubusercontent.com/31559354/38208371-d7a0ab1a-367e-11e8-89a4-934b3f8592bd.jpg)

Thanks.

**Comment by Mudassir32** [comment]
I think even after stretching the video if you draw lines at a proper area,
mean by selecting proper threshold values, it should work accurately.

You can upload the video again and again by changing video threshold value,
the beauty of this code is that you have an option to select your required
threshold values.

To understand the mystery of threshold values a time is required, need to
explore the code.

If you are interested do let me know I will sort out your problems and can
do further alteration in code.

Email: mudasar.mehmood@gmail.com


--
Regards

Mudassir Mehmood

**Comment by guruvishnuvardan** [comment]
Hi, Can I count Motorbikes with this solution?

**Comment by Mudassir32** [comment]
Yes, but you need to alter the code.If you need any services do let me know.

--
Regards

Mudassir Mehmood

**Comment by AdilahMohd** [comment]
Hi, why i cant upload the video. The video does not appear when open video. the error message state like below

**OpenCV Error: Assertion failed (ssize.area() > 0) in cv::resize, file C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\imgproc\src\imgwarp.cpp, line 3229
Exception in thread "AWT-EventQueue-0" CvException [org.opencv.core.CvException: cv::Exception: C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\imgproc\src\imgwarp.cpp:3229: error: (-215) ssize.area() > 0 in function cv::resize
]
	at org.opencv.imgproc.Imgproc.resize_1(Native Method)
	at org.opencv.imgproc.Imgproc.resize(Imgproc.java:2716)
	at GUI.lambda$loadFile$1(GUI.java:553)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
BUILD SUCCESSFUL (total time: 1 minute 15 seconds)**
